//ADMIN
//ADD MERCHANT
export const ADMIN_ADD_MERCHANT_REQUEST = "ADMIN_ADD_MERCHANT_REQUEST";
export const ADMIN_ADD_MERCHANT_SUCCESS = "ADMIN_ADD_MERCHANT_SUCCESS";
export const ADMIN_ADD_MERCHANT_FAILURE = "ADMIN_ADD_MERCHANT_FAILURE";
export const ADMIN_ADD_MERCHANT_RESET = "ADMIN_ADD_MERCHANT_RESET";

//ADMIN GET ALL MERCHANTS
export const ADMIN_MERCHANT_LIST_REQUEST = "ADMIN_MERCHANT_LIST_REQUEST";
export const ADMIN_MERCHANT_LIST_SUCCESS = "ADMIN_MERCHANT_LIST_SUCCESS";
export const ADMIN_MERCHANT_LIST_FAILURE = "ADMIN_MERCHANT_LIST_FAILURE";

//GET MERCHANT BY ID
export const ADMIN_GET_MERCHANT_REQUEST = "ADMIN_GET_MERCHANT_REQUEST";
export const ADMIN_GET_MERCHANT_SUCCESS = "ADMIN_GET_MERCHANT_SUCCESS";
export const ADMIN_GET_MERCHANT_FAILURE = "ADMIN_GET_MERCHANT_FAILURE";

//UPDATE MERCHANT
export const ADMIN_UPDATE_MERCHANT_STATUS_REQUEST =
  "ADMIN_UPDATE_MERCHANT_STATUS_REQUEST";
export const ADMIN_UPDATE_MERCHANT_STATUS_SUCCESS =
  "ADMIN_UPDATE_MERCHANT_STATUS_SUCCESS";
export const ADMIN_UPDATE_MERCHANT_STATUS_FAILURE =
  "ADMIN_UPDATE_MERCHANT_STATUS_FAILURE";
export const ADMIN_UPDATE_MERCHANT_STATUS_RESET =
  "ADMIN_UPDATE_MERCHANT_STATUS_RESET";

//DELETE MERCHANT
export const ADMIN_DELETE_MERCHANT_REQUEST = "ADMIN_DELETE_MERCHANT_REQUEST";
export const ADMIN_DELETE_MERCHANT_SUCCESS = "ADMIN_DELETE_MERCHANT_SUCCESS";
export const ADMIN_DELETE_MERCHANT_FAILURE = "ADMIN_DELETE_MERCHANT_FAILURE";
