//ADMIN GET ALL NOTIFICATIONS
export const ADMIN_GET_NOTIFICATIONS_REQUEST = "ADMIN_GET_NOTIFICATIONS_REQUEST";
export const ADMIN_GET_NOTIFICATIONS_SUCCESS = "ADMIN_GET_NOTIFICATIONS_SUCCESS";
export const ADMIN_GET_NOTIFICATIONS_FAILURE = "ADMIN_GET_NOTIFICATIONS_FAILURE";

//ADMIN UPDATE NOTIFICATIONS
export const ADMIN_UPDATE_NOTIFICATIONS_REQUEST = "ADMIN_UPDATE_NOTIFICATIONS_REQUEST";
export const ADMIN_UPDATE_NOTIFICATIONS_SUCCESS = "ADMIN_UPDATE_NOTIFICATIONS_SUCCESS";
export const ADMIN_UPDATE_NOTIFICATIONS_FAILURE = "ADMIN_UPDATE_NOTIFICATIONS_FAILURE";
export const ADMIN_UPDATE_NOTIFICATIONS_RESET = "ADMIN_UPDATE_NOTIFICATIONS_RESET";
