export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";


export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_CREATE_PAYMENT_REQUEST = "ORDER_CREATE_PAYMENT_REQUEST";
export const ORDER_CREATE_PAYMENT_SUCCESS = "ORDER_CREATE_PAYMENT_SUCCESS";
export const ORDER_CREATE_PAYMENT_FAILURE = "ORDER_CREATE_PAYMENT_FAILURE";
export const ORDER_CREATE_PAYMENT_RESET = "ORDER_CREATE_PAYMENT_RESET";

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAILURE = "ORDER_LIST_FAILURE";
export const ORDER_LIST_RESET = "ORDER_LIST_RESET";

//ADMIN GET ALL ORDERS
export const ADMIN_ORDER_LIST_REQUEST = "ADMIN_ORDER_LIST_REQUEST";
export const ADMIN_ORDER_LIST_SUCCESS = "ADMIN_ORDER_LIST_SUCCESS";
export const ADMIN_ORDER_LIST_FAILURE = "ADMIN_ORDER_LIST_FAILURE";
export const ADMIN_ORDER_LIST_RESET = "ADMIN_ORDER_LIST_RESET";

//ADMIN GET ORDERS DETAILS
export const ADMIN_ORDER_DETAILS_REQUEST = "ADMIN_ORDER_DETAILS_REQUEST";
export const ADMIN_ORDER_DETAILS_SUCCESS = "ADMIN_ORDER_DETAILS_SUCCESS";
export const ADMIN_ORDER_DETAILS_FAILURE = "ADMIN_ORDER_DETAILS_FAILURE";
